PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS TRIP_GUIDES;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS TRIP;
DROP TABLE IF EXISTS GUIDE;

CREATE TABLE GUIDE (
  GUIDE_NUM TEXT PRIMARY KEY,
  LAST_NAME TEXT,
  FIRST_NAME TEXT,
  ADDRESS TEXT,
  CITY TEXT,
  STATE TEXT,
  POSTAL_CODE TEXT,
  PHONE_NUM TEXT,
  HIRE_DATE TEXT
);

CREATE TABLE CUSTOMER (
  CUSTOMER_NUM TEXT PRIMARY KEY,
  LAST_NAME TEXT,
  FIRST_NAME TEXT,
  ADDRESS TEXT,
  CITY TEXT,
  STATE TEXT,
  POSTAL_CODE TEXT,
  PHONE_NUM TEXT,
  BALANCE NUMERIC
);

CREATE TABLE TRIP (
  TRIP_ID TEXT PRIMARY KEY,
  TRIP_NAME TEXT,
  START_LOCATION TEXT,
  STATE TEXT,
  DISTANCE NUMERIC,
  MAX_GRP_SIZE NUMERIC,
  TYPE TEXT,
  SEASON TEXT
);

CREATE TABLE RESERVATION (
  RESERV_NUM TEXT PRIMARY KEY,
  TRIP_ID TEXT,
  CUSTOMER_NUM TEXT,
  TRIP_DATE TEXT,
  NUM_PERSONS NUMERIC,
  FOREIGN KEY (TRIP_ID) REFERENCES TRIP(TRIP_ID),
  FOREIGN KEY (CUSTOMER_NUM) REFERENCES CUSTOMER(CUSTOMER_NUM)
);

CREATE TABLE TRIP_GUIDES (
  TRIP_ID TEXT,
  GUIDE_NUM TEXT,
  PRIMARY KEY (TRIP_ID, GUIDE_NUM),
  FOREIGN KEY (TRIP_ID) REFERENCES TRIP(TRIP_ID),
  FOREIGN KEY (GUIDE_NUM) REFERENCES GUIDE(GUIDE_NUM)
);

INSERT INTO GUIDE VALUES ('G1', 'Harrison', 'George', '123 Pine St', 'Mesa', 'AZ', '85123', '602-123-4567', '2005-05-22');
INSERT INTO CUSTOMER VALUES ('C1', 'Smith', 'John', '456 Oak St', 'Phoenix', 'AZ', '85001', '602-987-6543', 500.00);
INSERT INTO TRIP VALUES ('T1', 'Desert Adventure', 'Phoenix', 'AZ', 120, 15, 'Hiking', 'Winter');
INSERT INTO RESERVATION VALUES ('R1', 'T1', 'C1', '2025-01-10', 3);
INSERT INTO TRIP_GUIDES VALUES ('T1', 'G1');
