PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS SERVICE_REQUEST;
DROP TABLE IF EXISTS SERVICE_CATEGORY;
DROP TABLE IF EXISTS OWNER;
DROP TABLE IF EXISTS CONDO_UNIT;
DROP TABLE IF EXISTS LOCATION;

CREATE TABLE LOCATION (
  LOCATION_ID TEXT PRIMARY KEY,
  LOCATION_NAME TEXT,
  ADDRESS TEXT,
  CITY TEXT,
  STATE TEXT,
  POSTAL_CODE TEXT
);

CREATE TABLE CONDO_UNIT (
  UNIT_ID TEXT PRIMARY KEY,
  LOCATION_ID TEXT,
  UNIT_NO TEXT,
  SQUARE_FEET NUMERIC,
  BEDROOMS NUMERIC,
  BATHROOMS NUMERIC,
  MAX_PERSONS NUMERIC,
  WEEKLY_RATE NUMERIC,
  FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

CREATE TABLE OWNER (
  OWNER_ID TEXT PRIMARY KEY,
  FIRST_NAME TEXT,
  LAST_NAME TEXT,
  PHONE TEXT,
  EMAIL TEXT
);

CREATE TABLE SERVICE_CATEGORY (
  CATEGORY_ID TEXT PRIMARY KEY,
  CATEGORY_NAME TEXT,
  DESCRIPTION TEXT
);

CREATE TABLE SERVICE_REQUEST (
  REQUEST_ID TEXT PRIMARY KEY,
  UNIT_ID TEXT,
  CATEGORY_ID TEXT,
  REQUEST_DATE TEXT,
  STATUS TEXT,
  FOREIGN KEY (UNIT_ID) REFERENCES CONDO_UNIT(UNIT_ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORY(CATEGORY_ID)
);

INSERT INTO LOCATION VALUES ('L1', 'Beach View', '123 Ocean Ave', 'San Diego', 'CA', '92101');
INSERT INTO CONDO_UNIT VALUES ('U1', 'L1', '101', 1200, 2, 2, 6, 1500.00);
INSERT INTO OWNER VALUES ('O1', 'Alice', 'Johnson', '555-1234', 'alice@example.com');
INSERT INTO SERVICE_CATEGORY VALUES ('SC1', 'Plumbing', 'Fix leaks and pipes');
INSERT INTO SERVICE_REQUEST VALUES ('SR1', 'U1', 'SC1', '2025-01-12', 'Open');
